server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productservice_db
    username: postgres
    password: root

  
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/

custom:
  app-name: Product Service


instance:
  prefer-ip-address: true
  
